version: '3'

services:

  backendserver:
    build: /back2/
    ports:
           - "8087:8087"

    restart: always
  frontend:
    build: /frontAngularPfe/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "4200:4200"
    restart: always
